### ISSUE TITLE
Unable to install miservice

### ISSUE THREAD

**Issue by Annabelle0726** [yihong0618/MiService#14]
<img width="960" alt="error" src="https://github.com/yihong0618/MiService/assets/97329962/97d066f6-3cfe-4c86-9c5f-f86da62cef3b">
PS C:\Projects\PythonProjects\AI\MiService> pip3 install miservice
Collecting miservice
  Using cached miservice-2.0.1.tar.gz (12 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error                            
                                                                 
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "c:\users\0real\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <
module>
          main()
        File "c:\users\0real\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in m
ain
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "c:\users\0real\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in g
et_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\0real\AppData\Local\Temp\pip-build-env-exux2q9a\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_bui
ld_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\0real\AppData\Local\Temp\pip-build-env-exux2q9a\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires 
          self.run_setup()
        File "C:\Users\0real\AppData\Local\Temp\pip-build-env-exux2q9a\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\0real\AppData\Local\Temp\pip-build-env-exux2q9a\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 25, in <module>
        File "c:\users\0real\appdata\local\programs\python\python39\lib\pathlib.py", line 1256, in read_text
          return f.read()
        File "c:\users\0real\appdata\local\programs\python\python39\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 2062: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

The last sentence suggests that this error is likely not a problem with pip.

**Comment by yihong0618** [comment]
pip install miservice-fork

**Comment by Annabelle0726** [comment]
yes I did install that but 

![image](https://github.com/yihong0618/MiService/assets/97329962/43337fd6-3f98-4b6c-a129-12fbee174971)

**Comment by Annabelle0726** [comment]
I tried to make a new folder, but this time it says can not clone your repository
<img width="960" alt="bce237026e39f41c2f7a21379471fcf" src="https://github.com/yihong0618/MiService/assets/97329962/8150d58f-6a6a-427d-be96-2205da70a4c7">

**Comment by yihong0618** [comment]
you do not need clone, just pip install

**Comment by Annabelle0726** [comment]
![image](https://github.com/yihong0618/MiService/assets/97329962/374ce0c9-f910-47ff-b4db-ff5c82b65e25)

It doesn't return anything from micli.py, it should get the DID right?

**Comment by yihong0618** [comment]
just ‘micli list’
your password is in the screenshot I deleted it for you

**Comment by yihong0618** [comment]
> ![image](https://private-user-images.githubusercontent.com/97329962/287592501-9da11b91-7ad5-45b6-809f-d6bacfef5c9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2NjUzMTMsIm5iZiI6MTcwMTY2NTAxMywicGF0aCI6Ii85NzMyOTk2Mi8yODc1OTI1MDEtOWRhMTFiOTEtN2FkNS00NWI2LTgwOWYtZDZiYWNmZWY1YzlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDA0NDMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlMWYzN2VmMTQ5ZTY1YjM5ZTE3NjJhYjJkMzRjZGRiNzVlNzM0NjMwYzc2MjkxZTUxYWQxOGNkOGQ2NTNjZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sfQHW4S-zXndw-0zfZUGE1IPlkM3gLaJQ8bGYEIF1sQ) sorry it fails again

You need set username and password in every session

**Comment by Annabelle0726** [comment]
<img width="960" alt="image" src="https://github.com/yihong0618/MiService/assets/97329962/7ae31325-5c4f-46cc-b322-364becb57254">
still

**Comment by frostming** [comment]
Search for how to set env var in powershell... You usage is wrong

**Comment by Annabelle0726** [comment]
do you mean I need to add a quotation around my username and password? it doesn't work for me

**Comment by yihong0618** [comment]
https://www.tutorialspoint.com/how-to-set-environment-variables-using-powershell
