### ISSUE TITLE
账号密码的问题总是这样

### ISSUE THREAD

**Issue by jjiikkkk** [yihong0618/MiService#6]
Exception on login None: {'qs': '%3Fsid%3Dxiaomiio%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '0psXfr43eNI0IX6q9Suk3qWbRqU=', 'sid': 'xiaomiio', 'result': 'error', 'captchaUrl': None, 'callback': 'https://sts.api.io.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}
Traceback (most recent call last):
  File "/home/linux1/.local/lib/python3.10/site-packages/miservice/miaccount.py", line 69, in login
    raise Exception(resp)
Exception: {'qs': '%3Fsid%3Dxiaomiio%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '0psXfr43eNI0IX6q9Suk3qWbRqU=', 'sid': 'xiaomiio', 'result': 'error', 'captchaUrl': None, 'callback': 'https://sts.api.io.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}
Error https://api.io.mi.com/app/home/device_list: Login failed
linux1@gongzhonghao-xiaomi:~/MiService$

**Comment by jjiikkkk** [comment]
oot@iZbp1fl3af51xt5mw5zz61Z:~/xiaogpt/MiService# micli.py list
Exception on login None: {'qs': '%3Fsid%3Dxiaomiio%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '0psXfr43eNI0IX6q9Suk3qWbRqU=', 'sid': 'xiaomiio', 'result': 'error', 'captchaUrl': None, 'callback': 'https://sts.api.io.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/miservice/miaccount.py", line 69, in login
    raise Exception(resp)
Exception: {'qs': '%3Fsid%3Dxiaomiio%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '0psXfr43eNI0IX6q9Suk3qWbRqU=', 'sid': 'xiaomiio', 'result': 'error', 'captchaUrl': None, 'callback': 'https://sts.api.io.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}   现在换成国内的VPS了，还是这样 无语了

**Comment by jjiikkkk** [comment]
Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/miservice/miaccount.py", line 69, in login raise Exception(resp) 总是这么错

**Comment by jjiikkkk** [comment]
从腾讯云测试到华为云，用的本地SSH
